# This is a basic workflow to help you get started with Actions

name: Nuitka CI

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Compile:
    if: github.ref == 'refs/heads/master'
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out repository
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Python 3.9
        uses: actions/setup-python@v3.0.0
        with:
          python-version: 3.9.7
          architecture: x64
      - name: Install dependencies
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Replace broken dependencies
        shell: cmd
        run: |
          del C:\hostedtoolcache\windows\Python\3.9.7\x64\lib\site-packages\playsound.py
          copy D:\a\Bilibili-Online-Jukebox\Bilibili-Online-Jukebox\site-packages\playsound.py C:\hostedtoolcache\windows\Python\3.9.7\x64\lib\site-packages\
          del C:\hostedtoolcache\windows\Python\3.9.7\x64\lib\site-packages\pydub\utils.py
          copy D:\a\Bilibili-Online-Jukebox\Bilibili-Online-Jukebox\site-packages\pydub\utils.py C:\hostedtoolcache\windows\Python\3.9.7\x64\lib\site-packages\pydub\
      - name: Compile
        shell: cmd
        run: |
          setup.bat
      - name: Setup FFmpeg
        uses: Iamshankhadeep/setup-ffmpeg@v1.1
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "5.0"
      - name: Move FFmpeg
        shell: cmd
        run: |
          mkdir D:\a\Bilibili-Online-Jukebox\Bilibili-Online-Jukebox\out\dm_console.dist\bin
          copy C:\hostedtoolcache\windows\ffmpeg\5.0\x64\ffmpeg.exe D:\a\Bilibili-Online-Jukebox\Bilibili-Online-Jukebox\out\dm_console.dist\bin\
          copy C:\hostedtoolcache\windows\ffmpeg\5.0\x64\ffprobe.exe D:\a\Bilibili-Online-Jukebox\Bilibili-Online-Jukebox\out\dm_console.dist\bin\
      - name: Archive Release
        uses: TheDoctor0/zip-release@0.6.1
        with: 
          filename: BilibiliOnlineJukebox.zip
          path: dm_console.dist\*
          directory: D:\a\Bilibili-Online-Jukebox\Bilibili-Online-Jukebox\out\
          type: zip
      - name: Upload artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: BilibiliOnlineJukebox
          path: D:\a\Bilibili-Online-Jukebox\Bilibili-Online-Jukebox\out\dm_console.dist\*
      - name: Prerelease
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "0.4.12.3"
          prerelease: false
          title: "0.4.12.3"
          files: |
            D:/a/Bilibili-Online-Jukebox/Bilibili-Online-Jukebox/out/BilibiliOnlineJukebox.zip
