# This is a basic workflow to help you get started with Actions

name: Nuitka CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out repository
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Archive Release
        uses: TheDoctor0/zip-release@0.6.1
        with: 
          filename: BilibiliOnlineJukebox.zip
          path: Bilibili-Online-Jukebox\
          directory: D:\a\Bilibili-Online-Jukebox\
          type: zip
      - name: Dir
        shell: cmd
        run: |
          dir D:\a\Bilibili-Online-Jukebox\
      - name: Prerelease
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "current-binary-package"
          prerelease: true
          title: "Latest Development Build"
          files: |
            D:/a/Bilibili-Online-Jukebox/BilibiliOnlineJukebox.zip
